spring:
    datasource:
        url: jdbc:h2:mem:testdb
        driverClassName: org.h2.Driver
        username: sa
        password: password
    jpa:
        database-platform: org.hibernate.dialect.H2Dialect

    h2:
        console:
            enabled: true
            path: /h2-console
    jackson:
        property-naming-strategy: SNAKE_CASE

system-config:
    oauth2:
       token-generator: hash 



